# Generated by Django 6.0.3 on 2026-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_call_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
