# Generated by Django 6.0.3 on 2026-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_message_tool_call_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tool_call_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tool_name',
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20),
        ),
    ]
