# Generated by Django 6.0.3 on 2026-07-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_address_line_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
