# Generated by Django 6.0.3 on 2026-04-15 05:56

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('primary_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='MobileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.mobile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=190)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.mobile')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.specification')),
            ],
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['slug'], name='products_mo_slug_559e26_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['price'], name='products_mo_price_e6b5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['created_at'], name='products_mo_created_fc87a1_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileimage',
            index=models.Index(fields=['mobile'], name='products_mo_mobile__48c283_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobileimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('mobile',), name='unique_primary_image_per_mobile'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='mobilespecification',
            index=models.Index(fields=['mobile'], name='products_mo_mobile__fc5720_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilespecification',
            index=models.Index(fields=['specification'], name='products_mo_specifi_ba851d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilespecification',
            unique_together={('mobile', 'specification')},
        ),
    ]
